# Configures GHC to be the 8.2 variant from the Docker image
# See https://hub.docker.com/r/tweag/linear-types/

# resolver: nightly-2017-12-20
# compiler: ghc-8.2

resolver: lts-12.1
compiler: ghc-8.4

system-ghc: true
docker:
  enable: true
#  image: tweag/linear-types:0.1.6
#  image: tweag/linear-types:0.1.8
  image: mylinear

packages:
- '.'
